export const BASE_API_PATH = 'http://localhost:8081/api';
export const API_REGISTER_PATH = BASE_API_PATH + '/auth/register';
export const API_LOGIN_PATH = BASE_API_PATH + '/auth/authenticate';
export const API_RESET_PASSWORD_PATH = BASE_API_PATH + '/auth/reset-password';
export const API_CATEGORIES_PATH = BASE_API_PATH + '/categories';
export const API_VENUES_PATH = BASE_API_PATH + '/venues';
export const API_ORGANIZATIONS_PATH = BASE_API_PATH + '/organizations';
export const API_EVENTS_PATH = BASE_API_PATH + '/events';
export const API_TICKETS_PATH = BASE_API_PATH + '/tickets';
export const API_USERS_PATH = BASE_API_PATH + '/users';
export const API_USER_BAN_PATH = (username: string) => `${API_USERS_PATH}/ban`;
export const API_USER_ORGANIZATIONS_PATH = (userId: string) => `${API_USERS_PATH}/${userId}/organizations`;
export const API_USER_PATH_VAR = (userId: string) => `${API_USERS_PATH}/${userId}`;
export const API_USER_SECURITY_PATH = (userId: string) => `${API_USER_PATH_VAR(userId) + '/security'}`;